//This file was generated by script mkregs.py

//address width
`define iob_pcie_swreg_ADDR_W 2

//address macros
//Write addresses
`define _TXCHNL_DATA_ADDR 0
`define _TXCHNL_LEN_ADDR 4
//Read Addresses
`define _RXCHNL_DATA_ADDR 0
`define _RXCHNL_LEN_ADDR 4

//register/mem data width
`define _TXCHNL_DATA_W 32
`define _TXCHNL_LEN_W 32
`define _RXCHNL_DATA_W 32
`define _RXCHNL_LEN_W 32

//mem address width
